// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5FSfYL8c61NWcoj1B_KkIoml04npXrwY',
    appId: '1:740335140773:web:445af4d1925886781b324c',
    messagingSenderId: '740335140773',
    projectId: 'ticketflow-c2d76',
    authDomain: 'ticketflow-c2d76.firebaseapp.com',
    storageBucket: 'ticketflow-c2d76.firebasestorage.app',
    measurementId: 'G-TXCYKQJQCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjUQ3gUbM6IWveGQApUehXNryeXv0Wo0c',
    appId: '1:740335140773:android:076666f836ed63d21b324c',
    messagingSenderId: '740335140773',
    projectId: 'ticketflow-c2d76',
    storageBucket: 'ticketflow-c2d76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-gRyQZNa8NK7GmCnD2x5eiDAOljwXqoI',
    appId: '1:740335140773:ios:9b91ea4c019412bb1b324c',
    messagingSenderId: '740335140773',
    projectId: 'ticketflow-c2d76',
    storageBucket: 'ticketflow-c2d76.firebasestorage.app',
    iosBundleId: 'com.example.ticketFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-gRyQZNa8NK7GmCnD2x5eiDAOljwXqoI',
    appId: '1:740335140773:ios:9b91ea4c019412bb1b324c',
    messagingSenderId: '740335140773',
    projectId: 'ticketflow-c2d76',
    storageBucket: 'ticketflow-c2d76.firebasestorage.app',
    iosBundleId: 'com.example.ticketFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5FSfYL8c61NWcoj1B_KkIoml04npXrwY',
    appId: '1:740335140773:web:619932c9c1c7a2bc1b324c',
    messagingSenderId: '740335140773',
    projectId: 'ticketflow-c2d76',
    authDomain: 'ticketflow-c2d76.firebaseapp.com',
    storageBucket: 'ticketflow-c2d76.firebasestorage.app',
    measurementId: 'G-YTP7BPYL08',
  );
}
